[package]
name = "peaq-pay"
version = "0.0.1"
edition = "2021"
description = 'A package for processing payments and settlements on peaq network. Also works with any substrate based network that implements multisog pallets.'
authors = ['peaq network <https://github.com/peaqnetwork>']
homepage = 'https://peaq.network/'
license = 'Apache-2.0'
publish = false
repository = 'https://github.com/peaqnetwork/peaq-pay/'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
